"""empty message

Revision ID: 537586639b6a
Revises: 7fcae1cb89a0
Create Date: 2023-09-20 11:53:07.970700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537586639b6a'
down_revision = '7fcae1cb89a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
