"""empty message

Revision ID: 854eeada98ca
Revises: 66e62ef33011
Create Date: 2023-09-15 16:20:45.390361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854eeada98ca'
down_revision = '66e62ef33011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
