"""empty message

Revision ID: cefe971be906
Revises: 0be4e526916e
Create Date: 2023-09-21 07:40:07.812807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cefe971be906'
down_revision = '0be4e526916e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
